#!/bin/sh

# find location git is installed
alias internal_config_cmd='$(command -v git) --git-dir=/root/.cfg/ --work-tree=/'

conf() {
	# when adding a symlink, use the target instead
	if [ "$1" == "add" ] && [ -L "$2" ]; then
		internal_config_cmd add $(readlink -f "$2") "${@:3}"
	else
		internal_config_cmd "$@"
	fi
}

#conf config --local status.showUntrackedFiles no
#conf config status.showUntrackedFiles no

# OLD SAFE TO DELETE
